### ISSUE TITLE
Markup presence should not be checked on import time

### ISSUE THREAD

**Issue by Almad** [ella/django-markup#1]
If form using markupfield is imported before database is synced, following error occurs.

```
Traceback (most recent call last):
File "/usr/lib64/python2.6/site-packages/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
File "/usr/lib64/python2.6/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
File "/usr/lib64/python2.6/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
File "./../unit_project/tests/test_forms.py", line 4, in <module>
    from esus.phorum.forms import *
File "./../../esus/phorum/forms.py", line 28, in <module>
    class CommentCreationForm(forms.Form):
File "./../../esus/phorum/forms.py", line 33, in CommentCreationForm
    field_name="text",
File "/home/almad/project/django-markup/djangomarkup/fields.py", line 70, in __init__
    self.processor = TextProcessor.objects.get(name=syntax_processor_name or getattr(settings, "DEFAULT_MARKUP", "markdown"))
File "/home/almad/project/django/django/db/models/manager.py", line 120, in get
    return self.get_query_set().get(*args, **kwargs)
File "/home/almad/project/django/django/db/models/query.py", line 269, in get
    num = len(clone)
File "/home/almad/project/django/django/db/models/query.py", line 68, in __len__
    self._result_cache = list(self.iterator())
File "/home/almad/project/django/django/db/models/query.py", line 207, in iterator
    for row in self.query.results_iter():
File "/home/almad/project/django/django/db/models/sql/query.py", line 287, in results_iter
    for rows in self.execute_sql(MULTI):
File "/home/almad/project/django/django/db/models/sql/query.py", line 2359, in execute_sql
    cursor.execute(sql, params)
File "/home/almad/project/django/django/db/backends/util.py", line 19, in execute
    return self.cursor.execute(sql, params)
File "/home/almad/project/django/django/db/backends/sqlite3/base.py", line 193, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: djangomarkup_textprocessor
```

**Comment by Almad** [comment]
My bad - cause by absence of djangomarkup in INSTALLED_APPS.
